dir = "."
lang = "Rust"
organization_id = "ginger-society"
service_type = "RPCEndpoint"
spec_url = "/openapi.json"

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs]

[ws_refs]

[urls]
dev = "http://localhost:8080/iam-admin"
prod = "https://exampleapi.com"
prod_k8 = "https://exampleapi.com"
stage = "https://api-staging.gingersociety.org/iam-admin"
stage_k8 = "http://iam-service-api-service/iam-admin"

[urls_ws]
